/**
 * All auth specific paths are autogenerated here
 * documentation: https://better-auth-ui.com/integrations/next-js
 */

import { AuthView } from "@daveyplate/better-auth-ui";
import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";

export const dynamicParams = false;

export default async function AuthPage({
  params,
}: {
  params: Promise<{ path: string }>;
}) {
  const { path } = await params;
  return (
    <main
      className="h-screen w-full grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3  bg-gradient-to-br from-[#FBD276] via-[#FD947F] to-[#FB7186]
          bg-no-repeat bg-center bg-contain overflow-y-hidden "
    >
      <div
        className=" relative
          hidden md:flex 
         
        "
      >
        <div className="absolute right-[-5%] top-[80%] lg:right-[-35%] lg:top-[70%] -translate-y-1/2 md:w-[350px] md:h-[350px] lg:w-[450px] lg:h-[450px] xl:w-[550px] xl:h-[550px] 2xl:w-[650px] 2xl:h-[650px]">
          
        </div>
      </div>

      <div className=" lg:col-span-2 flex items-center justify-center md:rounded-l-4xl md:bg-[#fff] lg:p-6">
        <div className="w-full max-w-md h-full flex flex-col rounded-3xl p-4 md:p-8 pt-16 ">
          <h4 className="text-3xl text-slate-700  text-center">
            Client Portal
          </h4>

          <div className=" authCard flex-1 flex items-center justify-center">
            <AuthView
              path={path}
              classNames={{
                footer: "hidden",
              }}
            />
          </div>
        </div>
      </div>
    </main>
  );
}
